#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_lucky_number:
  path: /test/test
  controller: App\Controller\TestController::test

telegram_messages/get:
  path: /telegram/messages/get
  controller: App\Controller\Telegram\TelegramMessagesController::index
